<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_VUgEEDZiEeuv8qHxzG8oaA" name="Publicación de oferta laboral" version="2.0" author="diego" bonitaVersion="7.11.0" bonitaModelVersion="7.11.0-005" configId="ACED0005740010372E31312E302D303035372E31312E30">
    <elements xmi:type="process:Pool" xmi:id="_VUgEETZiEeuv8qHxzG8oaA" name="Publicación de oferta laboral" version="2.0">
      <elements xmi:type="process:Lane" xmi:id="_VUgEEjZiEeuv8qHxzG8oaA" name="Empleador" actor="_XqJa4DZkEeuv8qHxzG8oaA">
        <elements xmi:type="process:StartEvent" xmi:id="_VUgEEzZiEeuv8qHxzG8oaA" name="Necesidad publicar oferta" outgoing="_VUgEdDZiEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VUgEFDZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VUgEFTZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VUgEFjZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_VUgEFzZiEeuv8qHxzG8oaA" name="Genera información de oferta laboral" outgoing="_5UlKoDZjEeuv8qHxzG8oaA" incoming="_VUgEdDZiEeuv8qHxzG8oaA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VUgEGDZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VUgEGTZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VUgEGjZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VUgEGzZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VUgEHDZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VUgEHTZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VUgEHjZiEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VUgEHzZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_VUgEIDZiEeuv8qHxzG8oaA">
            <targetForm xmi:type="expression:Expression" xmi:id="_VUgEITZiEeuv8qHxzG8oaA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_VUgEIjZiEeuv8qHxzG8oaA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_VUgEIzZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_uNuK8DZjEeuv8qHxzG8oaA" name="Enviar información oferta laboral" outgoing="_-SRMoDZjEeuv8qHxzG8oaA" incoming="_5UlKoDZjEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_shsuATZjEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_shsuADZjEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_shsuAjZjEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_shsuAzZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_shsuBDZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_shsuBTZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_shsuBzZjEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_shsuBjZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_t0IUUDZlEeuv8qHxzG8oaA" name="Publicación denegada" incoming="_t0IUZTZlEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t0IUUTZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t0IUUjZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t0IUUzZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_t0IUWDZlEeuv8qHxzG8oaA" name="Receptar denegación de publicar oferta laboral" outgoing="_t0IUZTZlEeuv8qHxzG8oaA" incoming="_5aONsDZlEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_t0IUWTZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_t0IUWjZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_t0IUWzZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_t0IUXDZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_t0IUXTZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_t0IUXjZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_t0IUXzZlEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_t0IUYDZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_t0IUYTZlEeuv8qHxzG8oaA"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_7eS24zZoEeu-SrbsL0ASKA" name="Receptar denegación de publicar oferta laboral" outgoing="_QooGoDZpEeu-SrbsL0ASKA" incoming="_7eTd8zZoEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7eS25DZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7eS25TZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7eS25jZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7eS25zZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7eS26DZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7eS26TZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7eS26jZoEeu-SrbsL0ASKA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7eS26zZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_7eS27DZoEeu-SrbsL0ASKA"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_o-z5QDZnEeuv8qHxzG8oaA" name="Publicación denegada" incoming="_QooGoDZpEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_o-z5QTZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_o-z5QjZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_o-z5QzZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_V6cJEDZqEeu-SrbsL0ASKA" name="Receptar aprobación de oferta laboral publicada" outgoing="_oRSkkDZqEeu-SrbsL0ASKA" incoming="_ZWs0kDZqEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Uz4JoTZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Uz4JojZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Uz4JozZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Uz4JpDZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Uz4JpTZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Uz4JpjZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Uz4JpzZqEeu-SrbsL0ASKA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Uz4JqDZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_oRPhQDZqEeu-SrbsL0ASKA" name="Registro aprobado" incoming="_g55hEDirEeuNMZJmSxb2ug">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oRPhQjZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oRPhQTZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oRPhQzZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_M93QcDirEeuNMZJmSxb2ug" outgoing="_g55hEDirEeuNMZJmSxb2ug" incoming="_oRSkkDZqEeu-SrbsL0ASKA _IFQsgDZrEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_M94ekDirEeuNMZJmSxb2ug" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_M94ekTirEeuNMZJmSxb2ug" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_M94ekjirEeuNMZJmSxb2ug" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VUgEKDZiEeuv8qHxzG8oaA" name="Encargado del postulacion laboral" actor="_X88bEDZkEeuv8qHxzG8oaA">
        <elements xmi:type="process:SendTask" xmi:id="_VUgEUTZiEeuv8qHxzG8oaA" name="Enviar publicación oferta laboral" outgoing="_VUgEfTZiEeuv8qHxzG8oaA" incoming="_C-dBADirEeuNMZJmSxb2ug">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VUgEUjZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VUgEUzZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VUgEVDZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VUgEVTZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VUgEVjZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VUgEVzZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VUgEWDZiEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VUgEWTZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_-7izIDZjEeuv8qHxzG8oaA" name="Receptar información oferta laboral" outgoing="_3sWzIDZkEeuv8qHxzG8oaA" incoming="_-SRMoDZjEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-SNiQTZjEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-SNiQDZjEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-SNiQjZjEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-SNiQzZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-SNiRDZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-SNiRTZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-SNiRzZjEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-SNiRjZjEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4FivMDZkEeuv8qHxzG8oaA" name="Validar oferta laboral" outgoing="_OU8JkDZlEeuv8qHxzG8oaA" incoming="_3sWzIDZkEeuv8qHxzG8oaA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3sO3UjZkEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3sO3UTZkEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3sO3UzZkEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3sO3VDZkEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3sO3VTZkEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_3sO3VjZkEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_3sO3WDZkEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_3sO3VzZkEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4FjWSDZkEeuv8qHxzG8oaA">
            <targetForm xmi:type="expression:Expression" xmi:id="_4FjWSTZkEeuv8qHxzG8oaA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4FjWRzZkEeuv8qHxzG8oaA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4FjWSjZkEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_TsHCkDZlEeuv8qHxzG8oaA" name="Enviar denegación de publicar oferta laboral" outgoing="_5aONsDZlEeuv8qHxzG8oaA" incoming="_VUgEgzZiEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TsHCkTZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TsHCkjZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TsHCkzZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_TsHClDZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_TsHClTZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_TsHCljZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_TsHClzZlEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_TsHCmDZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_TsHCmTZlEeuv8qHxzG8oaA" name="Anulación">
            <correlation xmi:type="process:Correlation" xmi:id="_TsHCmjZlEeuv8qHxzG8oaA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_TsHCmzZlEeuv8qHxzG8oaA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_TsHCnDZlEeuv8qHxzG8oaA" name="Anular registro" content="Anular registro" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_TsHCnTZlEeuv8qHxzG8oaA" name="Invalidación registro" content="Invalidación registro" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_TsHCnjZlEeuv8qHxzG8oaA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_TsHCnzZlEeuv8qHxzG8oaA">
                <expressions xmi:type="expression:Expression" xmi:id="_TsHCoDZlEeuv8qHxzG8oaA" name="Anulación" content="Anulación" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_TsHCoTZlEeuv8qHxzG8oaA" name="1" content="1"/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_-bo5IDZlEeuv8qHxzG8oaA" name="Enviar oferta laboral validada por encargado" outgoing="_l3v3IDZmEeuv8qHxzG8oaA" incoming="_VUgEejZiEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WjjJwTZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WjjJwjZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WjjJwzZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_WjjJxDZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_WjjJxTZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_WjjJxjZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_WjjJxzZlEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_WjjJyDZlEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_v0W_UDZoEeu-SrbsL0ASKA" name="Recibir denegación de publicar oferta laboral" outgoing="__TFXIDZoEeu-SrbsL0ASKA" incoming="_vWohgDZoEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vV0pMTZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vV0pMDZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vV0pMjZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vV0pMzZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vV0pNDZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vV0pNTZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vV0pNzZoEeu-SrbsL0ASKA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vV0pNjZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_7eSP0DZoEeu-SrbsL0ASKA" name="Enviar denegación de publicar oferta laboral" outgoing="_7eTd8zZoEeu-SrbsL0ASKA" incoming="__TFXIDZoEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7eSP0TZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7eSP0jZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7eSP0zZoEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7eSP1DZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7eSP1TZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7eSP1jZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7eSP1zZoEeu-SrbsL0ASKA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7eSP2DZoEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_7eSP2TZoEeu-SrbsL0ASKA" name="Anulación">
            <correlation xmi:type="process:Correlation" xmi:id="_7eSP2jZoEeu-SrbsL0ASKA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_7eSP2zZoEeu-SrbsL0ASKA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_7eSP3DZoEeu-SrbsL0ASKA" name="Anular registro" content="Anular registro" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_7eSP3TZoEeu-SrbsL0ASKA" name="Invalidación registro" content="Invalidación registro" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_7eSP3jZoEeu-SrbsL0ASKA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_7eSP3zZoEeu-SrbsL0ASKA">
                <expressions xmi:type="expression:Expression" xmi:id="_7eSP4DZoEeu-SrbsL0ASKA" name="Anulación" content="Anulación" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_7eSP4TZoEeu-SrbsL0ASKA" name="1" content="1"/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_ycLgsDZpEeu-SrbsL0ASKA" name="Recibir aprobación de publicar oferta laboral" outgoing="_BE5dkDZqEeu-SrbsL0ASKA" incoming="_8SSDIDZpEeu-SrbsL0ASKA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ycLgsTZpEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ycLgsjZpEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ycLgszZpEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ycLgtDZpEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ycLgtTZpEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ycLgtjZpEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ycLgtzZpEeu-SrbsL0ASKA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ycLguDZpEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_FOLAEDZqEeu-SrbsL0ASKA" name="Registrar oferta  laboral validada" outgoing="_zr3nwDiqEeuNMZJmSxb2ug" incoming="_BE5dkDZqEeu-SrbsL0ASKA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VUgEKjZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VUgEKzZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VUgELDZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VUgELTZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VUgELjZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VUgELzZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VUgEMDZiEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VUgEMTZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_FOLnKTZqEeu-SrbsL0ASKA">
            <targetForm xmi:type="expression:Expression" xmi:id="_FOLnKjZqEeu-SrbsL0ASKA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_FOLnKDZqEeu-SrbsL0ASKA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_FOLnKzZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_J76hkDZqEeu-SrbsL0ASKA" name="Enviar aprobación de oferta laboral publicada" outgoing="_ZWs0kDZqEeu-SrbsL0ASKA" incoming="_BFf7UDirEeuNMZJmSxb2ug">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_J76hkTZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_J76hkjZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_J76hkzZqEeu-SrbsL0ASKA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_J76hlDZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_J76hlTZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_J76hljZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_J76hlzZqEeu-SrbsL0ASKA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_J76hmDZqEeu-SrbsL0ASKA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <events xmi:type="process:Message" xmi:id="_J76hmTZqEeu-SrbsL0ASKA" name="Anulación">
            <correlation xmi:type="process:Correlation" xmi:id="_J76hmjZqEeu-SrbsL0ASKA">
              <correlationAssociation xmi:type="expression:TableExpression" xmi:id="_J76hmzZqEeu-SrbsL0ASKA"/>
            </correlation>
            <targetProcessExpression xmi:type="expression:Expression" xmi:id="_J76hnDZqEeu-SrbsL0ASKA" name="Anular registro" content="Anular registro" returnTypeFixed="true"/>
            <targetElementExpression xmi:type="expression:Expression" xmi:id="_J76hnTZqEeu-SrbsL0ASKA" name="Invalidación registro" content="Invalidación registro" returnTypeFixed="true"/>
            <messageContent xmi:type="expression:TableExpression" xmi:id="_J76hnjZqEeu-SrbsL0ASKA">
              <expressions xmi:type="expression:ListExpression" xmi:id="_J76hnzZqEeu-SrbsL0ASKA">
                <expressions xmi:type="expression:Expression" xmi:id="_J76hoDZqEeu-SrbsL0ASKA" name="Anulación" content="Anulación" returnTypeFixed="true"/>
                <expressions xmi:type="expression:Expression" xmi:id="_J76hoTZqEeu-SrbsL0ASKA" name="1" content="1"/>
              </expressions>
            </messageContent>
          </events>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_UXipMDiqEeuNMZJmSxb2ug" name="Información validada" outgoing="_VUgEgzZiEeuv8qHxzG8oaA _VUgEejZiEeuv8qHxzG8oaA" incoming="_OU8JkDZlEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MiXYsTZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MiXYsjZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MiXYszZlEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_zq9BwDiqEeuNMZJmSxb2ug" outgoing="_BFf7UDirEeuNMZJmSxb2ug _C-dBADirEeuNMZJmSxb2ug" incoming="_zr3nwDiqEeuNMZJmSxb2ug">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zrDIYTiqEeuNMZJmSxb2ug" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zrDIYDiqEeuNMZJmSxb2ug" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zrDIYjiqEeuNMZJmSxb2ug" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VUgEYjZiEeuv8qHxzG8oaA" name="Gestor de la carrera" actor="_nfSHkDZkEeuv8qHxzG8oaA">
        <elements xmi:type="process:ReceiveTask" xmi:id="_pAH9UDZmEeuv8qHxzG8oaA" name="Receptar oferta laboral validada por encargado" outgoing="_GW9UcDZnEeuv8qHxzG8oaA" incoming="_l3v3IDZmEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h_X3bTZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h_X3bjZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h_X3bzZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_h_X3cDZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_h_X3cTZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_h_X3cjZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_h_X3czZmEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_h_X3dDZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Gz9ZgDZnEeuv8qHxzG8oaA" name="Validar oferta laboral" outgoing="_MmmtkDZnEeuv8qHxzG8oaA" incoming="_GW9UcDZnEeuv8qHxzG8oaA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GW6RITZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GW6RIDZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GW6RIjZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GW6RIzZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GW6RJDZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GW6RJTZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GW6RJzZnEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GW6RJjZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Gz-AkTZnEeuv8qHxzG8oaA">
            <targetForm xmi:type="expression:Expression" xmi:id="_Gz-AkjZnEeuv8qHxzG8oaA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Gz-AkDZnEeuv8qHxzG8oaA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Gz-AkzZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_MfXAoDZoEeuv8qHxzG8oaA" name="Enviar denegación de publicar oferta laboral" outgoing="_vWohgDZoEeu-SrbsL0ASKA" incoming="_h_fzMDZmEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QOfaQTZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QOfaQDZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QOfaQjZnEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QOfaQzZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QOfaRDZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QOfaRTZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QOfaRzZnEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QOfaRjZnEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_h_X3YDZmEeuv8qHxzG8oaA" name="Enviar aprobación de publicar oferta laboral" outgoing="_8SSDIDZpEeu-SrbsL0ASKA" incoming="_h_fzOTZmEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h_X3YTZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h_X3YjZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h_X3YzZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_h_X3ZDZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_h_X3ZTZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_h_X3ZjZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_h_X3ZzZmEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_h_X3aDZmEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_VtXzsDiqEeuNMZJmSxb2ug" name="Información validada" outgoing="_h_fzMDZmEeuv8qHxzG8oaA _h_fzOTZmEeuv8qHxzG8oaA" incoming="_MmmtkDZnEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h_X3gjZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h_X3gzZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h_X3hDZmEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="__brhMDZiEeuv8qHxzG8oaA" name="Postulante" actor="_owdbkDZkEeuv8qHxzG8oaA">
        <elements xmi:type="process:ReceiveTask" xmi:id="_VUgEYzZiEeuv8qHxzG8oaA" name="Receptar publicación oferta laboral" outgoing="_IFQsgDZrEeu-SrbsL0ASKA" incoming="_VUgEfTZiEeuv8qHxzG8oaA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VUgEZDZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VUgEZTZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VUgEZjZiEeuv8qHxzG8oaA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VUgEZzZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VUgEaDZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VUgEaTZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VUgEajZiEeuv8qHxzG8oaA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VUgEazZiEeuv8qHxzG8oaA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_VUgEcDZiEeuv8qHxzG8oaA">
        <targetForm xmi:type="expression:Expression" xmi:id="_VUgEcTZiEeuv8qHxzG8oaA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_VUgEcjZiEeuv8qHxzG8oaA">
        <targetForm xmi:type="expression:Expression" xmi:id="_VUgEczZiEeuv8qHxzG8oaA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VUgEdDZiEeuv8qHxzG8oaA" target="_VUgEFzZiEeuv8qHxzG8oaA" source="_VUgEEzZiEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VUgEdTZiEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VUgEdjZiEeuv8qHxzG8oaA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VUgEejZiEeuv8qHxzG8oaA" name="si" target="_-bo5IDZlEeuv8qHxzG8oaA" source="_UXipMDiqEeuNMZJmSxb2ug" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VUgEezZiEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VUgEfDZiEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VUgEfTZiEeuv8qHxzG8oaA" target="_VUgEYzZiEeuv8qHxzG8oaA" source="_VUgEUTZiEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VUgEfjZiEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VUgEfzZiEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VUgEgzZiEeuv8qHxzG8oaA" name="no" target="_TsHCkDZlEeuv8qHxzG8oaA" source="_UXipMDiqEeuNMZJmSxb2ug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VUgEhDZiEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VUgEhTZiEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5UlKoDZjEeuv8qHxzG8oaA" target="_uNuK8DZjEeuv8qHxzG8oaA" source="_VUgEFzZiEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5UlKoTZjEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5UlKojZjEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-SRMoDZjEeuv8qHxzG8oaA" target="_-7izIDZjEeuv8qHxzG8oaA" source="_uNuK8DZjEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-SRMoTZjEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_-SRMojZjEeuv8qHxzG8oaA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3sWzIDZkEeuv8qHxzG8oaA" target="_4FivMDZkEeuv8qHxzG8oaA" source="_-7izIDZjEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3sWzITZkEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3sWzIjZkEeuv8qHxzG8oaA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OU8JkDZlEeuv8qHxzG8oaA" target="_UXipMDiqEeuNMZJmSxb2ug" source="_4FivMDZkEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OU8woDZlEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_OU8woTZlEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_t0IUZTZlEeuv8qHxzG8oaA" target="_t0IUUDZlEeuv8qHxzG8oaA" source="_t0IUWDZlEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_t0IUZjZlEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_t0IUZzZlEeuv8qHxzG8oaA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5aONsDZlEeuv8qHxzG8oaA" target="_t0IUWDZlEeuv8qHxzG8oaA" source="_TsHCkDZlEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5aONsTZlEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5aONsjZlEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_h_fzMDZmEeuv8qHxzG8oaA" name="no" target="_MfXAoDZoEeuv8qHxzG8oaA" source="_VtXzsDiqEeuNMZJmSxb2ug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_h_fzMTZmEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_h_fzMjZmEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_h_fzOTZmEeuv8qHxzG8oaA" name="si" target="_h_X3YDZmEeuv8qHxzG8oaA" source="_VtXzsDiqEeuNMZJmSxb2ug" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_h_fzOjZmEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_h_fzOzZmEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_l3v3IDZmEeuv8qHxzG8oaA" target="_pAH9UDZmEeuv8qHxzG8oaA" source="_-bo5IDZlEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_l3v3ITZmEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_l3v3IjZmEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GW9UcDZnEeuv8qHxzG8oaA" target="_Gz9ZgDZnEeuv8qHxzG8oaA" source="_pAH9UDZmEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GW9UcTZnEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_GW9UcjZnEeuv8qHxzG8oaA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MmmtkDZnEeuv8qHxzG8oaA" target="_VtXzsDiqEeuNMZJmSxb2ug" source="_Gz9ZgDZnEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MmnUoDZnEeuv8qHxzG8oaA"/>
        <condition xmi:type="expression:Expression" xmi:id="_MmnUoTZnEeuv8qHxzG8oaA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vWohgDZoEeu-SrbsL0ASKA" target="_v0W_UDZoEeu-SrbsL0ASKA" source="_MfXAoDZoEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vWohgTZoEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_vWpIkDZoEeu-SrbsL0ASKA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7eTd8zZoEeu-SrbsL0ASKA" target="_7eS24zZoEeu-SrbsL0ASKA" source="_7eSP0DZoEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7eTd9DZoEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_7eTd9TZoEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__TFXIDZoEeu-SrbsL0ASKA" target="_7eSP0DZoEeu-SrbsL0ASKA" source="_v0W_UDZoEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__TFXITZoEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="__TFXIjZoEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QooGoDZpEeu-SrbsL0ASKA" target="_o-z5QDZnEeuv8qHxzG8oaA" source="_7eS24zZoEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QooGoTZpEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QooGojZpEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8SSDIDZpEeu-SrbsL0ASKA" target="_ycLgsDZpEeu-SrbsL0ASKA" source="_h_X3YDZmEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8SSDITZpEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_8SSDIjZpEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BE5dkDZqEeu-SrbsL0ASKA" target="_FOLAEDZqEeu-SrbsL0ASKA" source="_ycLgsDZpEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BE5dkTZqEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BE5dkjZqEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZWs0kDZqEeu-SrbsL0ASKA" target="_V6cJEDZqEeu-SrbsL0ASKA" source="_J76hkDZqEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZWs0kTZqEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZWs0kjZqEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oRSkkDZqEeu-SrbsL0ASKA" target="_M93QcDirEeuNMZJmSxb2ug" source="_V6cJEDZqEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oRSkkTZqEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_oRSkkjZqEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IFQsgDZrEeu-SrbsL0ASKA" target="_M93QcDirEeuNMZJmSxb2ug" source="_VUgEYzZiEeuv8qHxzG8oaA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IFRTkDZrEeu-SrbsL0ASKA"/>
        <condition xmi:type="expression:Expression" xmi:id="_IFRTkTZrEeu-SrbsL0ASKA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zr3nwDiqEeuNMZJmSxb2ug" target="_zq9BwDiqEeuNMZJmSxb2ug" source="_FOLAEDZqEeu-SrbsL0ASKA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zr414DiqEeuNMZJmSxb2ug"/>
        <condition xmi:type="expression:Expression" xmi:id="_zr5c8DiqEeuNMZJmSxb2ug" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BFf7UDirEeuNMZJmSxb2ug" target="_J76hkDZqEeu-SrbsL0ASKA" source="_zq9BwDiqEeuNMZJmSxb2ug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BFla4DirEeuNMZJmSxb2ug"/>
        <condition xmi:type="expression:Expression" xmi:id="_BFmB8DirEeuNMZJmSxb2ug" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_C-dBADirEeuNMZJmSxb2ug" target="_VUgEUTZiEeuv8qHxzG8oaA" source="_zq9BwDiqEeuNMZJmSxb2ug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_C-fdQDirEeuNMZJmSxb2ug"/>
        <condition xmi:type="expression:Expression" xmi:id="_C-fdQTirEeuNMZJmSxb2ug" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_g55hEDirEeuNMZJmSxb2ug" target="_oRPhQDZqEeu-SrbsL0ASKA" source="_M93QcDirEeuNMZJmSxb2ug">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_g6McADirEeuNMZJmSxb2ug"/>
        <condition xmi:type="expression:Expression" xmi:id="_g6O4QDirEeuNMZJmSxb2ug" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_XqJa4DZkEeuv8qHxzG8oaA" name="Empleador" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_X88bEDZkEeuv8qHxzG8oaA" name="Encargado de postulación laboral"/>
      <actors xmi:type="process:Actor" xmi:id="_nfSHkDZkEeuv8qHxzG8oaA" name="Gestor de la carrera"/>
      <actors xmi:type="process:Actor" xmi:id="_owdbkDZkEeuv8qHxzG8oaA" name="Postulante"/>
      <actors xmi:type="process:Actor" xmi:id="_WjiisDZlEeuv8qHxzG8oaA" name="Secretaria"/>
      <contract xmi:type="process:Contract" xmi:id="_VUgEmTZiEeuv8qHxzG8oaA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VUgEmjZiEeuv8qHxzG8oaA">
        <name xmi:type="expression:Expression" xmi:id="_VUgEmzZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VUgEnDZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VUgEnTZiEeuv8qHxzG8oaA">
        <name xmi:type="expression:Expression" xmi:id="_VUgEnjZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VUgEnzZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VUgEoDZiEeuv8qHxzG8oaA">
        <name xmi:type="expression:Expression" xmi:id="_VUgEoTZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VUgEojZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VUgEozZiEeuv8qHxzG8oaA">
        <name xmi:type="expression:Expression" xmi:id="_VUgEpDZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VUgEpTZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_VUgEpjZiEeuv8qHxzG8oaA">
        <name xmi:type="expression:Expression" xmi:id="_VUgEpzZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_VUgEqDZiEeuv8qHxzG8oaA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_VUgEqTZiEeuv8qHxzG8oaA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_VUgEqjZiEeuv8qHxzG8oaA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_VUgEqzZiEeuv8qHxzG8oaA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_VUgErDZiEeuv8qHxzG8oaA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_VUgErTZiEeuv8qHxzG8oaA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_VUgErjZiEeuv8qHxzG8oaA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_VUgErzZiEeuv8qHxzG8oaA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_VUgEsDZiEeuv8qHxzG8oaA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_VUgEsTZiEeuv8qHxzG8oaA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_VUgEsjZiEeuv8qHxzG8oaA" type="Process" element="_VUgEEDZiEeuv8qHxzG8oaA" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_VUgEszZiEeuv8qHxzG8oaA" type="2007" element="_VUgEETZiEeuv8qHxzG8oaA">
      <children xmi:type="notation:DecorationNode" xmi:id="_VUgEtDZiEeuv8qHxzG8oaA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_VUgEtTZiEeuv8qHxzG8oaA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_VUgEtjZiEeuv8qHxzG8oaA" type="3007" element="_VUgEEjZiEeuv8qHxzG8oaA">
          <children xmi:type="notation:DecorationNode" xmi:id="_VUgEtzZiEeuv8qHxzG8oaA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VUgEuDZiEeuv8qHxzG8oaA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_VUgEuTZiEeuv8qHxzG8oaA" type="3002" element="_VUgEEzZiEeuv8qHxzG8oaA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VUgEujZiEeuv8qHxzG8oaA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VUgEuzZiEeuv8qHxzG8oaA" x="49" y="-70"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgEvDZiEeuv8qHxzG8oaA" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VUgEvTZiEeuv8qHxzG8oaA" type="3005" element="_VUgEFzZiEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VUgEvjZiEeuv8qHxzG8oaA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgEvzZiEeuv8qHxzG8oaA" x="160" y="60" width="151" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uNwAIDZjEeuv8qHxzG8oaA" type="3025" element="_uNuK8DZjEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uNwAIjZjEeuv8qHxzG8oaA" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uNwAITZjEeuv8qHxzG8oaA" x="166" y="183" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_t0IUVDZlEeuv8qHxzG8oaA" type="3003" element="_t0IUUDZlEeuv8qHxzG8oaA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_t0IUVTZlEeuv8qHxzG8oaA" type="5025" element="_t0IUUDZlEeuv8qHxzG8oaA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_t0IUVjZlEeuv8qHxzG8oaA" x="-1" y="-62"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t0IUVzZlEeuv8qHxzG8oaA" x="435" y="83" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_t0IUYjZlEeuv8qHxzG8oaA" type="3026" element="_t0IUWDZlEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_t0IUYzZlEeuv8qHxzG8oaA" type="5012" element="_t0IUWDZlEeuv8qHxzG8oaA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_t0IUZDZlEeuv8qHxzG8oaA" x="360" y="172" width="180" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7eTd8DZoEeu-SrbsL0ASKA" type="3026" element="_7eS24zZoEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7eTd8TZoEeu-SrbsL0ASKA" type="5012" element="_7eS24zZoEeu-SrbsL0ASKA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7eTd8jZoEeu-SrbsL0ASKA" x="720" y="172" width="180" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o-z5RDZnEeuv8qHxzG8oaA" type="3003" element="_o-z5QDZnEeuv8qHxzG8oaA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_o-z5RTZnEeuv8qHxzG8oaA" type="5025" element="_o-z5QDZnEeuv8qHxzG8oaA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_o-z5RjZnEeuv8qHxzG8oaA" x="-1" y="-51"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o-z5RzZnEeuv8qHxzG8oaA" x="795" y="83" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_V6dXMDZqEeu-SrbsL0ASKA" type="3026" element="_V6cJEDZqEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_V6dXMjZqEeu-SrbsL0ASKA" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_V6dXMTZqEeu-SrbsL0ASKA" x="1337" y="185" width="182" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oRQIUDZqEeu-SrbsL0ASKA" type="3062" element="_oRPhQDZqEeu-SrbsL0ASKA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oRQIUjZqEeu-SrbsL0ASKA" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oRQIUzZqEeu-SrbsL0ASKA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oRQIUTZqEeu-SrbsL0ASKA" x="1862" y="216"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M-BogDirEeuNMZJmSxb2ug" type="3009" element="_M93QcDirEeuNMZJmSxb2ug" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_M-BogTirEeuNMZJmSxb2ug" type="5020" element="_M93QcDirEeuNMZJmSxb2ug">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_M-BogjirEeuNMZJmSxb2ug" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M-BogzirEeuNMZJmSxb2ug" x="1691" y="209"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VUgExDZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VUgExTZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VUgExjZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VUgExzZiEeuv8qHxzG8oaA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgEyDZiEeuv8qHxzG8oaA" x="53" y="10" width="1583" height="325"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VUgEyTZiEeuv8qHxzG8oaA" type="3007" element="_VUgEKDZiEeuv8qHxzG8oaA">
          <children xmi:type="notation:DecorationNode" xmi:id="_VUgEyjZiEeuv8qHxzG8oaA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VUgEyzZiEeuv8qHxzG8oaA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_VUgE3DZiEeuv8qHxzG8oaA" type="3025" element="_VUgEUTZiEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VUgE3TZiEeuv8qHxzG8oaA" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgE3jZiEeuv8qHxzG8oaA" x="1502" y="155" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-7jaODZjEeuv8qHxzG8oaA" type="3026" element="_-7izIDZjEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-7kBQDZjEeuv8qHxzG8oaA" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-7jaOTZjEeuv8qHxzG8oaA" x="164" y="27" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4FjWSzZkEeuv8qHxzG8oaA" type="3005" element="_4FivMDZkEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4FjWTTZkEeuv8qHxzG8oaA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4FjWTDZkEeuv8qHxzG8oaA" x="164" y="158" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_TsHCojZlEeuv8qHxzG8oaA" type="3025" element="_TsHCkDZlEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_TsHCozZlEeuv8qHxzG8oaA" type="5011" element="_TsHCkDZlEeuv8qHxzG8oaA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TsHCpDZlEeuv8qHxzG8oaA" x="368" y="21" width="164" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_-bpgMDZlEeuv8qHxzG8oaA" type="3025" element="_-bo5IDZlEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_-bpgMjZlEeuv8qHxzG8oaA" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_-bpgMTZlEeuv8qHxzG8oaA" x="531" y="155" width="160" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_v0XmYzZoEeu-SrbsL0ASKA" type="3026" element="_v0W_UDZoEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_v0XmZTZoEeu-SrbsL0ASKA" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_v0XmZDZoEeu-SrbsL0ASKA" x="723" y="150" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7eS24DZoEeu-SrbsL0ASKA" type="3025" element="_7eSP0DZoEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7eS24TZoEeu-SrbsL0ASKA" type="5011" element="_7eSP0DZoEeu-SrbsL0ASKA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7eS24jZoEeu-SrbsL0ASKA" x="728" y="27" width="164" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ycLguTZpEeu-SrbsL0ASKA" type="3026" element="_ycLgsDZpEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ycLgujZpEeu-SrbsL0ASKA" type="5012" element="_ycLgsDZpEeu-SrbsL0ASKA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ycLguzZpEeu-SrbsL0ASKA" x="938" y="155" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FOMOMDZqEeu-SrbsL0ASKA" type="3005" element="_FOLAEDZqEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_FOMOMjZqEeu-SrbsL0ASKA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FOMOMTZqEeu-SrbsL0ASKA" x="1190" y="155" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_J77IoDZqEeu-SrbsL0ASKA" type="3025" element="_J76hkDZqEeu-SrbsL0ASKA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_J77IoTZqEeu-SrbsL0ASKA" type="5011" element="_J76hkDZqEeu-SrbsL0ASKA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J77IojZqEeu-SrbsL0ASKA" x="1346" y="29" width="164" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UXwroDiqEeuNMZJmSxb2ug" type="3008" element="_UXipMDiqEeuNMZJmSxb2ug" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UXx5wDiqEeuNMZJmSxb2ug" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UXx5wTiqEeuNMZJmSxb2ug" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UXwroTiqEeuNMZJmSxb2ug" x="422" y="172" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zrIn8DiqEeuNMZJmSxb2ug" type="3009" element="_zq9BwDiqEeuNMZJmSxb2ug" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_zrM5YDiqEeuNMZJmSxb2ug" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zrM5YTiqEeuNMZJmSxb2ug" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zrIn8TiqEeuNMZJmSxb2ug" x="1406" y="172"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VUgE5zZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VUgE6DZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VUgE6TZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VUgE6jZiEeuv8qHxzG8oaA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgE6zZiEeuv8qHxzG8oaA" x="28" y="325" width="1693" height="301"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VUgE7DZiEeuv8qHxzG8oaA" type="3007" element="_VUgEYjZiEeuv8qHxzG8oaA">
          <children xmi:type="notation:DecorationNode" xmi:id="_VUgE7TZiEeuv8qHxzG8oaA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VUgE7jZiEeuv8qHxzG8oaA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_pAIkaDZmEeuv8qHxzG8oaA" type="3026" element="_pAH9UDZmEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pAIkajZmEeuv8qHxzG8oaA" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pAIkaTZmEeuv8qHxzG8oaA" x="529" y="26" width="164" height="83"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Gz-AlDZnEeuv8qHxzG8oaA" type="3005" element="_Gz9ZgDZnEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Gz-AljZnEeuv8qHxzG8oaA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Gz-AlTZnEeuv8qHxzG8oaA" x="545" y="205" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Mfb5IDZoEeuv8qHxzG8oaA" type="3025" element="_MfXAoDZoEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Mfb5IjZoEeuv8qHxzG8oaA" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Mfb5ITZoEeuv8qHxzG8oaA" x="727" y="27" width="165" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_h_X3aTZmEeuv8qHxzG8oaA" type="3025" element="_h_X3YDZmEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_h_X3ajZmEeuv8qHxzG8oaA" type="5011" element="_h_X3YDZmEeuv8qHxzG8oaA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h_X3azZmEeuv8qHxzG8oaA" x="947" y="33" width="166" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VtZB0DiqEeuNMZJmSxb2ug" type="3008" element="_VtXzsDiqEeuNMZJmSxb2ug" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VtZB0jiqEeuNMZJmSxb2ug" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VtZB0ziqEeuNMZJmSxb2ug" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VtZB0TiqEeuNMZJmSxb2ug" x="788" y="216" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VUgE9jZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VUgE9zZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VUgE-DZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VUgE-TZiEeuv8qHxzG8oaA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgE-jZiEeuv8qHxzG8oaA" x="53" y="594" width="1583" height="331"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="__bwZsDZiEeuv8qHxzG8oaA" type="3007" element="__brhMDZiEeuv8qHxzG8oaA">
          <children xmi:type="notation:DecorationNode" xmi:id="__bwZtTZiEeuv8qHxzG8oaA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="__bwZtjZiEeuv8qHxzG8oaA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_VUgE7zZiEeuv8qHxzG8oaA" type="3026" element="_VUgEYzZiEeuv8qHxzG8oaA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VUgE8DZiEeuv8qHxzG8oaA" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgE8TZiEeuv8qHxzG8oaA" x="1500" y="45" width="144" height="72"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="__bwZsTZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="__bwZsjZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="__bwZszZiEeuv8qHxzG8oaA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="__bwZtzZiEeuv8qHxzG8oaA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__bwZtDZiEeuv8qHxzG8oaA" x="28" y="957" width="1693" height="177"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_VUgE-zZiEeuv8qHxzG8oaA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_VUgE_DZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_VUgE_TZiEeuv8qHxzG8oaA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_VUgE_jZiEeuv8qHxzG8oaA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VUgE_zZiEeuv8qHxzG8oaA" width="2030" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_VUgFADZiEeuv8qHxzG8oaA"/>
    <edges xmi:type="notation:Connector" xmi:id="_VUgFATZiEeuv8qHxzG8oaA" type="4001" element="_VUgEdDZiEeuv8qHxzG8oaA" source="_VUgEuTZiEeuv8qHxzG8oaA" target="_VUgEvTZiEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VUgFAjZiEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VUgFAzZiEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VUgFBDZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VUgFBTZiEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VUgFCzZiEeuv8qHxzG8oaA" type="4001" element="_VUgEejZiEeuv8qHxzG8oaA" source="_UXwroDiqEeuNMZJmSxb2ug" target="_-bpgMDZlEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VUgFDDZiEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VUgFDTZiEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VUgFDjZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VUgFDzZiEeuv8qHxzG8oaA" points="[0, -12, -360, -5]$[331, -12, -29, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VUgFEDZiEeuv8qHxzG8oaA" id="(0.7906976744186046,0.4883720930232558)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VUgFETZiEeuv8qHxzG8oaA" id="(0.24166666666666667,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VUgFEjZiEeuv8qHxzG8oaA" type="4001" element="_VUgEfTZiEeuv8qHxzG8oaA" source="_VUgE3DZiEeuv8qHxzG8oaA" target="_VUgE7zZiEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VUgFEzZiEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VUgFFDZiEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VUgFFTZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VUgFFjZiEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__E9JoDZqEeu-SrbsL0ASKA" id="(0.5,0.9142857142857143)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VUgFHDZiEeuv8qHxzG8oaA" type="4001" element="_VUgEgzZiEeuv8qHxzG8oaA" source="_UXwroDiqEeuNMZJmSxb2ug" target="_TsHCojZlEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VUgFHTZiEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VUgFHjZiEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VUgFHzZiEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VUgFIDZiEeuv8qHxzG8oaA" points="[-22, -28, -306, 70]$[-22, -86, -306, 12]$[255, -86, -29, 12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VUgFITZiEeuv8qHxzG8oaA" id="(0.627906976744186,0.09302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5UlxsDZjEeuv8qHxzG8oaA" type="4001" element="_5UlKoDZjEeuv8qHxzG8oaA" source="_VUgEvTZiEeuv8qHxzG8oaA" target="_uNwAIDZjEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5UlxszZjEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5UlxtDZjEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5UlxsTZjEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5UlxsjZjEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5UmYwTZjEeuv8qHxzG8oaA" id="(0.5142857142857142,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-SRMozZjEeuv8qHxzG8oaA" type="4001" element="_-SRMoDZjEeuv8qHxzG8oaA" source="_uNwAIDZjEeuv8qHxzG8oaA" target="_-7jaODZjEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-SRzsDZjEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-SRzsTZjEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-SRMpDZjEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-SRMpTZjEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3sXaMDZkEeuv8qHxzG8oaA" type="4001" element="_3sWzIDZkEeuv8qHxzG8oaA" source="_-7jaODZjEeuv8qHxzG8oaA" target="_4FjWSzZkEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3sXaMzZkEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3sXaNDZkEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3sXaMTZkEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3sXaMjZkEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OU8wojZlEeuv8qHxzG8oaA" type="4001" element="_OU8JkDZlEeuv8qHxzG8oaA" source="_4FjWSzZkEeuv8qHxzG8oaA" target="_UXwroDiqEeuNMZJmSxb2ug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OU9XsDZlEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OU9XsTZlEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OU8wozZlEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OU8wpDZlEeuv8qHxzG8oaA" points="[0, 2, -160, 0]$[163, 2, 3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OU9-wDZlEeuv8qHxzG8oaA" id="(1.0,0.4027777777777778)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_t0IUaDZlEeuv8qHxzG8oaA" type="4001" element="_t0IUZTZlEeuv8qHxzG8oaA" source="_t0IUYjZlEeuv8qHxzG8oaA" target="_t0IUVDZlEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_t0IUaTZlEeuv8qHxzG8oaA" type="6001" element="_t0IUZTZlEeuv8qHxzG8oaA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_t0IUajZlEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_t0IUazZlEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_t0IUbDZlEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5aONszZlEeuv8qHxzG8oaA" type="4001" element="_5aONsDZlEeuv8qHxzG8oaA" source="_TsHCojZlEeuv8qHxzG8oaA" target="_t0IUYjZlEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5aONtjZlEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5aONtzZlEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5aONtDZlEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5aONtTZlEeuv8qHxzG8oaA" points="[-20, -28, 62, 117]$[-172, -142, -90, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5aPb0DZlEeuv8qHxzG8oaA" id="(0.5487804878048781,0.1927710843373494)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_h_fzMzZmEeuv8qHxzG8oaA" type="4001" element="_h_fzMDZmEeuv8qHxzG8oaA" source="_VtZB0DiqEeuNMZJmSxb2ug" target="_Mfb5IDZoEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_h_fzNDZmEeuv8qHxzG8oaA" type="6001" element="_h_fzMDZmEeuv8qHxzG8oaA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_h_fzNTZmEeuv8qHxzG8oaA" x="-8" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_h_fzNjZmEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_h_fzNzZmEeuv8qHxzG8oaA" points="[-27, 17, 16, 124]$[-27, -65, 16, 42]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_h_fzODZmEeuv8qHxzG8oaA" id="(0.627906976744186,0.09302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_h_fzPDZmEeuv8qHxzG8oaA" type="4001" element="_h_fzOTZmEeuv8qHxzG8oaA" source="_VtZB0DiqEeuNMZJmSxb2ug" target="_h_X3aTZmEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_h_fzPTZmEeuv8qHxzG8oaA" type="6001" element="_h_fzOTZmEeuv8qHxzG8oaA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_h_fzPjZmEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_h_fzPzZmEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_h_fzQDZmEeuv8qHxzG8oaA" points="[0, -12, -360, -5]$[331, -12, -29, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_h_fzQTZmEeuv8qHxzG8oaA" id="(0.8837209302325582,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_h_fzQjZmEeuv8qHxzG8oaA" id="(0.5384615384615384,0.9428571428571428)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_l3weMDZmEeuv8qHxzG8oaA" type="4001" element="_l3v3IDZmEeuv8qHxzG8oaA" source="_-bpgMDZlEeuv8qHxzG8oaA" target="_pAIkaDZmEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_l3weMzZmEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_l3weNDZmEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_l3weMTZmEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_l3weMjZmEeuv8qHxzG8oaA" points="[-18, 40, 53, -130]$[-76, 212, -5, 42]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sI0zoDZmEeuv8qHxzG8oaA" id="(0.5384615384615384,0.8857142857142857)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GW97gDZnEeuv8qHxzG8oaA" type="4001" element="_GW9UcDZnEeuv8qHxzG8oaA" source="_pAIkaDZmEeuv8qHxzG8oaA" target="_Gz-AlDZnEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GW97gzZnEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GW97hDZnEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GW97gTZnEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GW97gjZnEeuv8qHxzG8oaA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MmnUojZnEeuv8qHxzG8oaA" type="4001" element="_MmmtkDZnEeuv8qHxzG8oaA" source="_Gz-AlDZnEeuv8qHxzG8oaA" target="_VtZB0DiqEeuNMZJmSxb2ug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MmnUpTZnEeuv8qHxzG8oaA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MmnUpjZnEeuv8qHxzG8oaA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MmnUozZnEeuv8qHxzG8oaA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MmnUpDZnEeuv8qHxzG8oaA" points="[0, 0, -180, 10]$[176, -27, -4, -17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MmoiwDZnEeuv8qHxzG8oaA" id="(1.0,0.4696969696969697)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vWqWsDZoEeu-SrbsL0ASKA" type="4001" element="_vWohgDZoEeu-SrbsL0ASKA" source="_Mfb5IDZoEeuv8qHxzG8oaA" target="_v0XmYzZoEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vWqWszZoEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vWq9wDZoEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vWqWsTZoEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vWqWsjZoEeu-SrbsL0ASKA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7eUFADZoEeu-SrbsL0ASKA" type="4001" element="_7eTd8zZoEeu-SrbsL0ASKA" source="_7eS24DZoEeu-SrbsL0ASKA" target="_7eTd8DZoEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7eUFATZoEeu-SrbsL0ASKA" type="6001" element="_7eTd8zZoEeu-SrbsL0ASKA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7eUFAjZoEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7eUFAzZoEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7eUFBDZoEeu-SrbsL0ASKA" points="[-20, -28, 62, 117]$[-172, -142, -90, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7eUFBTZoEeu-SrbsL0ASKA" id="(0.5487804878048781,0.1927710843373494)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__TF-MDZoEeu-SrbsL0ASKA" type="4001" element="__TFXIDZoEeu-SrbsL0ASKA" source="_v0XmYzZoEeu-SrbsL0ASKA" target="_7eS24DZoEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__TF-MzZoEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__TGlQDZoEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__TF-MTZoEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__TF-MjZoEeu-SrbsL0ASKA" points="[-30, -28, 57, 63]$[-92, -49, -5, 42]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GstQEDZpEeu-SrbsL0ASKA" id="(0.4878048780487805,0.7951807228915663)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QootsDZpEeu-SrbsL0ASKA" type="4001" element="_QooGoDZpEeu-SrbsL0ASKA" source="_7eTd8DZoEeu-SrbsL0ASKA" target="_o-z5RDZnEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QootszZpEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QoottDZpEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QootsTZpEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QootsjZpEeu-SrbsL0ASKA" points="[-26, -31, 68, 84]$[-96, -120, -2, -5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qop70DZpEeu-SrbsL0ASKA" id="(0.5333333333333333,0.1978021978021978)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8SSqMDZpEeu-SrbsL0ASKA" type="4001" element="_8SSDIDZpEeu-SrbsL0ASKA" source="_h_X3aTZmEeuv8qHxzG8oaA" target="_ycLguTZpEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8SSqMzZpEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8SSqNDZpEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8SSqMTZpEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8SSqMjZpEeu-SrbsL0ASKA" points="[-19, -29, 64, 119]$[-170, -154, -87, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8SUfYDZpEeu-SrbsL0ASKA" id="(0.5060240963855421,0.1728395061728395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BE6EoDZqEeu-SrbsL0ASKA" type="4001" element="_BE5dkDZqEeu-SrbsL0ASKA" source="_ycLguTZpEeu-SrbsL0ASKA" target="_FOMOMDZqEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BE6EozZqEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BE6EpDZqEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BE6EoTZqEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BE6EojZqEeu-SrbsL0ASKA" points="[0, 4, -117, 0]$[97, 1, -20, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BE7SwDZqEeu-SrbsL0ASKA" id="(0.896551724137931,0.41379310344827586)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BE7SwTZqEeu-SrbsL0ASKA" id="(0.03896103896103896,0.5194805194805194)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZWtboDZqEeu-SrbsL0ASKA" type="4001" element="_ZWs0kDZqEeu-SrbsL0ASKA" source="_J77IoDZqEeu-SrbsL0ASKA" target="_V6dXMDZqEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZWtbozZqEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZWtbpDZqEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZWtboTZqEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZWtbojZqEeu-SrbsL0ASKA" points="[-22, -33, 60, 123]$[-173, -155, -91, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bCWeEDZqEeu-SrbsL0ASKA" id="(0.4878048780487805,0.13253012048192772)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aCkcEDZqEeu-SrbsL0ASKA" id="(0.521978021978022,0.9891304347826086)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oRTLoDZqEeu-SrbsL0ASKA" type="4001" element="_oRSkkDZqEeu-SrbsL0ASKA" source="_V6dXMDZqEeu-SrbsL0ASKA" target="_M-BogDirEeuNMZJmSxb2ug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oRTLozZqEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oRTLpDZqEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oRTLoTZqEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oRTLojZqEeu-SrbsL0ASKA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_OR1ZwDirEeuNMZJmSxb2ug" id="(0.13953488372093023,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IFRTkjZrEeu-SrbsL0ASKA" type="4001" element="_IFQsgDZrEeu-SrbsL0ASKA" source="_VUgE7zZiEeuv8qHxzG8oaA" target="_M-BogDirEeuNMZJmSxb2ug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IFRTlTZrEeu-SrbsL0ASKA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IFRTljZrEeu-SrbsL0ASKA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IFRTkzZrEeu-SrbsL0ASKA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IFRTlDZrEeu-SrbsL0ASKA" points="[0, 0, -65, 826]$[63, -841, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IFShsDZrEeu-SrbsL0ASKA" id="(1.0,0.3888888888888889)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zsBYwDiqEeuNMZJmSxb2ug" type="4001" element="_zr3nwDiqEeuNMZJmSxb2ug" source="_FOMOMDZqEeu-SrbsL0ASKA" target="_zrIn8DiqEeuNMZJmSxb2ug" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zsFDIDiqEeuNMZJmSxb2ug" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zsFqMDiqEeuNMZJmSxb2ug" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zsBYwTiqEeuNMZJmSxb2ug" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zsBYwjiqEeuNMZJmSxb2ug" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BFrhgDirEeuNMZJmSxb2ug" type="4001" element="_BFf7UDirEeuNMZJmSxb2ug" source="_zrIn8DiqEeuNMZJmSxb2ug" target="_J77IoDZqEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BFuk0DirEeuNMZJmSxb2ug" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BFvL4DirEeuNMZJmSxb2ug" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BFrhgTirEeuNMZJmSxb2ug" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BFrhgjirEeuNMZJmSxb2ug" points="[-1, -8, 20, 122]$[-13, -88, 8, 42]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BF7ZIDirEeuNMZJmSxb2ug" id="(0.3023255813953488,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_C-jusDirEeuNMZJmSxb2ug" type="4001" element="_C-dBADirEeuNMZJmSxb2ug" source="_zrIn8DiqEeuNMZJmSxb2ug" target="_VUgE3DZiEeuv8qHxzG8oaA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_C-juszirEeuNMZJmSxb2ug" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_C-kVwDirEeuNMZJmSxb2ug" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_C-jusTirEeuNMZJmSxb2ug" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_C-jusjirEeuNMZJmSxb2ug" points="[-13, 1, -120, 15]$[84, -14, -23, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_C-oAIDirEeuNMZJmSxb2ug" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_C-oAITirEeuNMZJmSxb2ug" id="(0.16428571428571428,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_g6k2gDirEeuNMZJmSxb2ug" type="4001" element="_g55hEDirEeuNMZJmSxb2ug" source="_M-BogDirEeuNMZJmSxb2ug" target="_oRQIUDZqEeu-SrbsL0ASKA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_g60HEDirEeuNMZJmSxb2ug" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_g60uIDirEeuNMZJmSxb2ug" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_g6mrsDirEeuNMZJmSxb2ug" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_g6mrsTirEeuNMZJmSxb2ug" points="[-7, 0, -150, 5]$[141, -20, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_g7p0kDirEeuNMZJmSxb2ug" id="(0.9767441860465116,0.46511627906976744)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
